### ISSUE TITLE
Release Date not working properly

### ISSUE THREAD

**Issue by SsLeaf** [NikkelM/Notion-Steam-API-Integration#50]
Seems like it puts a random date on games that haven't been released, even if the release date is already confirmed 

Examples:
Today (March 12) I tried to look for Atelier Ryza 3 (App ID = 1999770), the release date is confirmed to March 23 2023 (in 10 days), yet on my notion database appears as february 28 (Already released) when running the index.js

Also with Sea of stars (1244090), release set on steam to August 29 2023 (in 6 months), but on database appears as already released on February 29 2023

**Comment by SsLeaf** [comment]
Possible solutions for other cases: 
- If the game will be released during the year, put in notion that it will be released on December 31 of that year 
- If the game has no release date, leave the space blank (I have not tested what happens in this case with the actual code)

**Comment by NikkelM** [comment]
Thanks for the report and the detailed description! It looks like the integration was using the last recorded update to the game's store page if the release is set for a future date.
I've fixed this in the latest release, so now the following behaviour should be observed:
- For past release dates, the release date provided by the Steam store API is now used, which is not as specific as the one used before, but more reliable. Some release dates may change slightly, so if you want to be up-to-date, you may want to consider resetting the local database.
- For games with future release dates, three different cases are handled:
1. DD MMM, YYYY (e.g. 23 Mar, 2023), this will be interpreted as 23/03/2023
2. MMMM YYYY (e.g. August 2023), this will be interpreted as 01/08/2023
3. YYYY (e.g. 2023), this will be interpreted as 31/12/2023
- Games with no release date set or dates that are not dates (e.g. 'To be announced'), the release date property will be left blank.

Due to the change in the API that is used, the `format` property of the `releaseDate` configuration option is now deprecated, so you will need to remove it to run the integration.
Let me know if you find any other bugs or issues! :)
