### ISSUE TITLE
Would it be possible to get the amount of reviews?

### ISSUE THREAD

**Issue by timbuh** [NikkelM/Notion-Steam-API-Integration#56]
I'm planning on using this plugin soon to make a competitor analysis for a future project. Having the amount of reviews would allow me to calculate a rough estimate of the amount of sales. So would this be possible to add?

Thank you so much for making this and I can't wait to test it out!!

PS Are there resources / a more expanded guide on how to integrate plugins like this into Notion? I'm fairly new so a lot of the tasks described in the setup are kinda vague to me

**Comment by NikkelM** [comment]
Hi @timbuh - sorry for the late reply, I did not get a notification for this request. I've just now released [a new version of the integration](https://github.com/NikkelM/Notion-Steam-API-Integration/releases/tag/v1.6.0) that offers a number of new ways to format the review score, take a look at the `reviewScore` section in the Readme.

Regarding your second question - do you mean how to add an existing integration to your database, or how to build a new integration? What steps exactly in the setup guide are you having issues with? Perhaps I can improve the guide for the future.

If you're comfortable with scripting and would like a more direct way of getting the number of reviews for a list of games, you might want to consider writing your own little script instead of going the extra way through Notion, depending on how you need the data formatted - take a look at [the API endpoint](https://github.com/NikkelM/Notion-Steam-API-Integration/blob/1bdc0c65d23f608a4c0211f97fbc48b38c2eea17/js/steamAPI.js#L56) the integration uses.
